language: go

go:
  - "1.15"

env:
  global:
    - GO111MODULE=on
    - PGPORT=5432
    - PGUSER=postgres
    - PGPASSWORD=
    - PGDATABASE=postgres
    - MYUSER=travis
    - MYPASSWORD=

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - go mod download

script:
  - ./build+test.sh
